-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  doctor_id uuid,
  department_id uuid,
  room_id uuid,
  appointment_type text NOT NULL CHECK (appointment_type = ANY (ARRAY['consultation'::text, 'follow_up'::text, 'emergency'::text, 'procedure'::text, 'imaging'::text, 'laboratory'::text, 'surgery'::text, 'physiotherapy'::text])),
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::appointment_status,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  reason text,
  notes text,
  reminder_sent boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  department_specific_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  workflow_status character varying NOT NULL DEFAULT 'scheduled'::character varying,
  clinical_reference_type character varying,
  clinical_reference_id uuid,
  referring_department_id uuid,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT appointments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT appointments_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT appointments_referring_department_id_fkey FOREIGN KEY (referring_department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  description text,
  phone_extension text,
  location text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['medication'::text, 'equipment'::text, 'supplies'::text, 'consumables'::text, 'lab_supplies'::text, 'office'::text])),
  subcategory text,
  unit text NOT NULL,
  quantity integer NOT NULL DEFAULT 0,
  min_stock integer NOT NULL DEFAULT 0,
  max_stock integer,
  unit_cost numeric DEFAULT 0,
  unit_price numeric DEFAULT 0,
  supplier text,
  manufacturer text,
  expiration_date date,
  batch_number text,
  storage_location text,
  requires_prescription boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_id uuid NOT NULL,
  transaction_id uuid,
  file_name text NOT NULL,
  file_url text NOT NULL,
  document_type text NOT NULL DEFAULT 'other'::text,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_documents_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_documents_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT inventory_documents_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.inventory_transactions(id),
  CONSTRAINT inventory_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['in'::text, 'out'::text, 'adjustment'::text, 'transfer'::text, 'return'::text, 'disposal'::text, 'prescription_dispense'::text, 'sale'::text])),
  quantity integer NOT NULL,
  previous_quantity integer NOT NULL,
  new_quantity integer NOT NULL,
  reference_type text,
  reference_id text,
  notes text,
  performed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  service_code text,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL UNIQUE,
  patient_id uuid NOT NULL,
  appointment_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::invoice_status,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  amount_paid numeric DEFAULT 0,
  payment_method text,
  payment_reference text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  due_date date NOT NULL,
  issued_date date NOT NULL DEFAULT CURRENT_DATE,
  paid_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT invoices_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.lab_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  code character varying NOT NULL UNIQUE,
  description text,
  sample_type USER-DEFINED DEFAULT 'blood'::lab_sample_type,
  color character varying DEFAULT 'blue'::character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lab_order_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  test_id uuid,
  is_custom boolean DEFAULT false,
  custom_name character varying,
  custom_price numeric,
  custom_category_id uuid,
  sample_collected boolean DEFAULT false,
  sample_collected_at timestamp with time zone,
  sample_id character varying,
  collected_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_order_details_pkey PRIMARY KEY (id),
  CONSTRAINT lab_order_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.lab_orders(id),
  CONSTRAINT lab_order_details_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.lab_test_catalog(id),
  CONSTRAINT lab_order_details_collected_by_fkey FOREIGN KEY (collected_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  patient_id uuid NOT NULL,
  doctor_id uuid,
  order_date timestamp with time zone DEFAULT now(),
  priority USER-DEFINED DEFAULT 'routine'::lab_priority,
  status USER-DEFINED DEFAULT 'pending'::lab_order_status,
  notes text,
  total_amount numeric,
  payment_status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  appointment_id uuid,
  completed_by uuid,
  completed_at timestamp with time zone,
  CONSTRAINT lab_orders_pkey PRIMARY KEY (id),
  CONSTRAINT lab_orders_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT lab_orders_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.profiles(id),
  CONSTRAINT lab_orders_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.lab_parameters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  test_id uuid NOT NULL,
  name character varying NOT NULL,
  code character varying,
  unit character varying,
  reference_min numeric,
  reference_max numeric,
  reference_text character varying,
  method character varying,
  sort_order integer DEFAULT 0,
  is_critical_below numeric,
  is_critical_above numeric,
  decimal_places integer DEFAULT 2,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_parameters_pkey PRIMARY KEY (id),
  CONSTRAINT lab_parameters_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.lab_test_catalog(id)
);
CREATE TABLE public.lab_result_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  result_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_type character varying,
  file_size integer,
  storage_path text NOT NULL,
  description text,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_result_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT lab_result_attachments_result_id_fkey FOREIGN KEY (result_id) REFERENCES public.lab_results(id),
  CONSTRAINT lab_result_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_detail_id uuid NOT NULL,
  parameter_id uuid,
  value_text text,
  value_numeric numeric,
  status USER-DEFINED DEFAULT 'pending'::lab_result_status,
  result_date timestamp with time zone DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_results_pkey PRIMARY KEY (id),
  CONSTRAINT lab_results_order_detail_id_fkey FOREIGN KEY (order_detail_id) REFERENCES public.lab_order_details(id),
  CONSTRAINT lab_results_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.lab_parameters(id),
  CONSTRAINT lab_results_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_test_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  category_id uuid,
  sample_type USER-DEFINED DEFAULT 'blood'::lab_sample_type,
  container_type character varying,
  volume_required character varying,
  processing_time_hours integer DEFAULT 24,
  price numeric,
  requires_fasting boolean DEFAULT false,
  instructions text,
  preparation text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  duration_hours integer DEFAULT 24,
  preparation_required text,
  CONSTRAINT lab_test_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT lab_test_catalog_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.lab_categories(id)
);
CREATE TABLE public.medical_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  appointment_id uuid,
  doctor_id uuid,
  visit_date timestamp with time zone NOT NULL DEFAULT now(),
  record_type text NOT NULL CHECK (record_type = ANY (ARRAY['consultation'::text, 'progress_note'::text, 'procedure'::text, 'discharge'::text, 'referral'::text, 'lab_result'::text, 'imaging_result'::text, 'physiotherapy'::text])),
  chief_complaint text,
  history_of_present_illness text,
  physical_examination text,
  vital_signs jsonb DEFAULT '{}'::jsonb,
  diagnosis jsonb DEFAULT '[]'::jsonb,
  icd_codes ARRAY,
  treatment_plan text,
  prescriptions text,
  recommendations text,
  notes text,
  private_notes text,
  follow_up_required boolean DEFAULT false,
  follow_up_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medical_records_pkey PRIMARY KEY (id),
  CONSTRAINT medical_records_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medical_records_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.patient_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  author_id uuid NOT NULL,
  author_name text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  medical_record_number text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone text NOT NULL,
  dob date NOT NULL,
  gender USER-DEFINED,
  address text,
  city text,
  emergency_contact_name text,
  emergency_contact_phone text,
  blood_type text,
  allergies ARRAY,
  insurance_provider text,
  insurance_policy_number text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  dni numeric UNIQUE,
  CONSTRAINT patients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  provider_method_id character varying NOT NULL UNIQUE,
  last4 character varying,
  brand character varying,
  bank_name character varying,
  iban_prefix character varying,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_refunds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying NOT NULL DEFAULT 'EUR'::character varying,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::payment_status,
  provider_refund_id character varying,
  reason text NOT NULL,
  notes text,
  processed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT payment_refunds_pkey PRIMARY KEY (id),
  CONSTRAINT payment_refunds_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.payment_transactions(id),
  CONSTRAINT payment_refunds_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  currency character varying NOT NULL DEFAULT 'EUR'::character varying,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::payment_status,
  payment_method USER-DEFINED NOT NULL,
  provider character varying NOT NULL DEFAULT 'STRIPE'::character varying,
  provider_transaction_id character varying,
  provider_payment_intent_id character varying,
  provider_customer_id character varying,
  description text,
  customer_email character varying,
  customer_name character varying,
  customer_phone character varying,
  reference_type USER-DEFINED,
  reference_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  refunded_amount numeric DEFAULT 0,
  refund_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_event_id character varying NOT NULL UNIQUE,
  event_type character varying NOT NULL,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error_message text,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.physio_alert_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  alert_type character varying NOT NULL,
  severity character varying DEFAULT 'medium'::character varying,
  conditions jsonb NOT NULL DEFAULT '{}'::jsonb,
  message_template text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT physio_alert_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.physio_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alert_rule_id uuid,
  patient_id uuid NOT NULL,
  treatment_plan_id uuid,
  session_id uuid,
  alert_type character varying NOT NULL,
  severity character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  resolution_notes text,
  triggered_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT physio_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT physio_alerts_alert_rule_id_fkey FOREIGN KEY (alert_rule_id) REFERENCES public.physio_alert_rules(id),
  CONSTRAINT physio_alerts_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT physio_alerts_treatment_plan_id_fkey FOREIGN KEY (treatment_plan_id) REFERENCES public.physio_treatment_plans(id),
  CONSTRAINT physio_alerts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.physio_sessions(id),
  CONSTRAINT physio_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.physio_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  therapist_id uuid,
  room_id uuid,
  department_id uuid,
  session_type character varying NOT NULL DEFAULT 'treatment'::character varying,
  status character varying NOT NULL DEFAULT 'scheduled'::character varying,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT physio_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT physio_appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT physio_appointments_therapist_id_fkey FOREIGN KEY (therapist_id) REFERENCES public.profiles(id),
  CONSTRAINT physio_appointments_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.physio_rooms(id),
  CONSTRAINT physio_appointments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.physio_clinical_protocols (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  code character varying NOT NULL UNIQUE,
  description text,
  category character varying NOT NULL,
  body_region character varying,
  evidence_level character varying,
  total_sessions integer,
  session_duration_minutes integer DEFAULT 60,
  phases jsonb NOT NULL DEFAULT '[]'::jsonb,
  therapeutic_objectives ARRAY,
  contraindications ARRAY,
  precautions text,
  required_equipment ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT physio_clinical_protocols_pkey PRIMARY KEY (id)
);
CREATE TABLE public.physio_equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  brand text,
  model text,
  serial_number text,
  treatment_type_id uuid,
  specifications jsonb,
  parameters_template jsonb,
  location text,
  status text DEFAULT 'available'::text,
  purchase_date date,
  last_maintenance_date date,
  next_maintenance_date date,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT physio_equipment_pkey PRIMARY KEY (id),
  CONSTRAINT physio_equipment_treatment_type_id_fkey FOREIGN KEY (treatment_type_id) REFERENCES public.physio_treatment_types(id)
);
CREATE TABLE public.physio_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  target_muscle_group ARRAY,
  body_region text,
  difficulty_level text,
  instructions text,
  video_url text,
  image_url text,
  parameters_template jsonb,
  contraindications ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT physio_exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.physio_functional_evolution (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  subjective_assessment text NOT NULL,
  objective_findings text NOT NULL,
  assessment text NOT NULL,
  treatment_plan text NOT NULL,
  pain_before integer CHECK (pain_before >= 0 AND pain_before <= 10),
  pain_after integer CHECK (pain_after >= 0 AND pain_after <= 10),
  rom_measurements jsonb DEFAULT '[]'::jsonb,
  strength_grade jsonb DEFAULT '[]'::jsonb,
  session_objectives ARRAY,
  objectives_achieved ARRAY,
  patient_response text,
  tolerance text,
  adverse_reactions text,
  therapist_signature uuid,
  signed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT physio_functional_evolution_pkey PRIMARY KEY (id),
  CONSTRAINT physio_functional_evolution_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.physio_sessions(id),
  CONSTRAINT physio_functional_evolution_therapist_signature_fkey FOREIGN KEY (therapist_signature) REFERENCES public.profiles(id)
);
CREATE TABLE public.physio_informed_consents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  treatment_plan_id uuid,
  medical_record_id uuid,
  consent_type character varying NOT NULL DEFAULT 'treatment'::character varying,
  procedure_description text NOT NULL,
  risks ARRAY,
  benefits ARRAY,
  alternatives ARRAY,
  signed_by_patient boolean DEFAULT false,
  signed_by_representative boolean DEFAULT false,
  representative_name character varying,
  representative_dni character varying,
  valid_from date NOT NULL DEFAULT CURRENT_DATE,
  valid_until date,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT physio_informed_consents_pkey PRIMARY KEY (id),
  CONSTRAINT physio_informed_consents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT physio_informed_consents_treatment_plan_id_fkey FOREIGN KEY (treatment_plan_id) REFERENCES public.physio_treatment_plans(id),
  CONSTRAINT physio_informed_consents_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.physio_medical_records(id)
);
CREATE TABLE public.physio_medical_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  therapist_id uuid,
  department_id uuid,
  chief_complaint text,
  pain_location character varying,
  pain_scale_baseline integer CHECK (pain_scale_baseline >= 0 AND pain_scale_baseline <= 10),
  pain_duration character varying,
  pain_type character varying,
  pain_characteristics text,
  surgical_history text,
  traumatic_history text,
  medical_history text,
  family_history text,
  precautions text,
  physical_examination text,
  postural_evaluation text,
  rom_measurements jsonb,
  strength_grade jsonb,
  neurological_screening text,
  special_tests text,
  vas_score integer CHECK (vas_score >= 0 AND vas_score <= 10),
  oswestry_score integer CHECK (oswestry_score >= 0 AND oswestry_score <= 100),
  dash_score numeric CHECK (dash_score >= 0::numeric AND dash_score <= 100::numeric),
  womac_score numeric CHECK (womac_score >= 0::numeric AND womac_score <= 96::numeric),
  roland_morris_score integer CHECK (roland_morris_score >= 0 AND roland_morris_score <= 24),
  clinical_diagnosis text,
  functional_limitations text,
  patient_expectations text,
  informed_consent_signed boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  informed_consent_date timestamp with time zone,
  informed_consent_file_url text,
  informed_consent_file_name text,
  allergies jsonb,
  icd10_codes jsonb,
  short_term_goals jsonb,
  long_term_goals jsonb,
  contraindications jsonb,
  CONSTRAINT physio_medical_records_pkey PRIMARY KEY (id),
  CONSTRAINT physio_medical_records_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT physio_medical_records_therapist_id_fkey FOREIGN KEY (therapist_id) REFERENCES public.profiles(id),
  CONSTRAINT physio_medical_records_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.physio_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  room_type character varying NOT NULL DEFAULT 'treatment'::character varying,
  capacity integer NOT NULL DEFAULT 1,
  equipment ARRAY DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT physio_rooms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.physio_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid,
  patient_id uuid NOT NULL,
  therapist_id uuid NOT NULL,
  subjective text,
  objective text,
  analysis text,
  plan text,
  pain_level integer CHECK (pain_level >= 0 AND pain_level <= 10),
  body_region character varying,
  techniques_applied ARRAY DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  medical_record_id uuid,
  session_number integer,
  session_date date,
  session_time time without time zone,
  duration_minutes integer DEFAULT 45,
  is_initial_session boolean DEFAULT false,
  is_reassessment boolean DEFAULT false,
  functional_score integer,
  pain_location character varying,
  rom_affected character varying,
  muscle_strength_grade integer CHECK (muscle_strength_grade >= 0 AND muscle_strength_grade <= 5),
  muscle_group character varying,
  modality character varying,
  treatment_plan_id uuid,
  exercises_applied ARRAY,
  equipment_used ARRAY,
  treatments_detail jsonb,
  CONSTRAINT physio_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT physio_sessions_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.medical_records(id),
  CONSTRAINT physio_sessions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT physio_sessions_therapist_id_fkey FOREIGN KEY (therapist_id) REFERENCES public.profiles(id),
  CONSTRAINT physio_sessions_treatment_plan_id_fkey FOREIGN KEY (treatment_plan_id) REFERENCES public.physio_treatment_plans(id),
  CONSTRAINT physio_sessions_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.physio_techniques (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  treatment_type_id uuid,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  parameters_schema jsonb,
  results_schema jsonb,
  default_duration_minutes integer,
  contraindications ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT physio_techniques_pkey PRIMARY KEY (id),
  CONSTRAINT physio_techniques_treatment_type_id_fkey FOREIGN KEY (treatment_type_id) REFERENCES public.physio_treatment_types(id)
);
CREATE TABLE public.physio_treatment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  medical_record_id uuid,
  prescribing_doctor_id uuid,
  department_id uuid,
  diagnosis_code character varying,
  diagnosis_description text,
  plan_type character varying NOT NULL DEFAULT 'rehabilitation'::character varying,
  clinical_objective text,
  start_date date NOT NULL,
  expected_end_date date,
  actual_end_date date,
  status character varying NOT NULL DEFAULT 'indicated'::character varying CHECK (status = ANY (ARRAY['indicated'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'paused'::character varying, 'cancelled'::character varying])),
  sessions_per_week integer DEFAULT 3,
  total_sessions_prescribed integer,
  initial_assessment text,
  baseline_rom text,
  baseline_functional_score integer,
  progress_notes ARRAY,
  outcome_measures ARRAY,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT physio_treatment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT physio_treatment_plans_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT physio_treatment_plans_prescribing_doctor_id_fkey FOREIGN KEY (prescribing_doctor_id) REFERENCES public.profiles(id),
  CONSTRAINT physio_treatment_plans_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT physio_treatment_plans_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.physio_medical_records(id)
);
CREATE TABLE public.physio_treatment_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  category text,
  icon_url text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT physio_treatment_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  medical_record_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  doctor_id uuid,
  medication_id uuid,
  medication_name text NOT NULL,
  dosage text NOT NULL,
  frequency text NOT NULL,
  duration text NOT NULL,
  quantity_prescribed integer NOT NULL,
  quantity_dispensed integer DEFAULT 0,
  refills_allowed integer DEFAULT 0,
  refills_used integer DEFAULT 0,
  instructions text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partially_dispensed'::text, 'dispensed'::text, 'cancelled'::text, 'expired'::text])),
  prescribed_date timestamp with time zone NOT NULL DEFAULT now(),
  dispensed_date timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.medical_records(id),
  CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT prescriptions_medication_id_fkey FOREIGN KEY (medication_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text NOT NULL,
  role character varying NOT NULL,
  specialty text,
  license_number text,
  phone text,
  avatar_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_number text NOT NULL,
  department_id uuid,
  room_type text NOT NULL CHECK (room_type = ANY (ARRAY['consultation'::text, 'emergency'::text, 'surgery'::text, 'recovery'::text, 'hospitalization'::text, 'imaging'::text, 'laboratory'::text])),
  capacity integer DEFAULT 1,
  current_occupancy integer DEFAULT 0,
  status text DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'occupied'::text, 'maintenance'::text, 'reserved'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT rooms_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);